"""/nav-history — daily NAV series read from the `nav_snapshots` collection.

NAV snapshots are generated by seed_demo + can be appended daily by a job. If
the collection is empty (e.g. fresh boot before seed completes), we return an
empty list so the chart shows the empty-state rather than fake data.
"""
from datetime import timedelta

from fastapi import APIRouter, Depends, Query

from auth import CurrentUser
from db import col, NAV_SNAPSHOTS

from ._deps import iso, require_dashboard, utc_now

router = APIRouter()


@router.get("/nav-history")
async def get_nav_history(days: int = Query(90, ge=1, le=365),
                          _: CurrentUser = Depends(require_dashboard)):
    now = utc_now().replace(hour=0, minute=0, second=0, microsecond=0)
    start = now - timedelta(days=days)
    cur = col(NAV_SNAPSHOTS).find(
        {"date": {"$gte": start.strftime("%Y-%m-%d")}},
        {"_id": 0, "date": 1, "nav": 1},
    ).sort("date", 1)
    items = await cur.to_list(400)
    items = items[-days:]
    return {"items": items, "total": len(items), "source": "nav_snapshots"}
